name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore /p:Version=${{ steps.gitversion.outputs.assemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }}
      - name: Test
        run: dotnet test -c Release --no-build
      - name: Publish
        run: dotnet publish -c Release /p:Version=${{ steps.gitversion.outputs.assemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }}
      - name: Choco Package
        uses: crazy-max/ghaction-chocolatey@v1.4.2
        with:
          args: pack xkpasswd.cli\bin\Release\net5.0\win-x64\publish\xkpasswd.cli.nuspec --Version ${{ steps.gitversion.outputs.nuGetVersion }}
      - name: Tag build
        run: |
          git tag v${{ steps.gitversion.outputs.semVer }}
          git push origin  refs/tags/v${{ steps.gitversion.outputs.semVer }}
      - name: Push Package To hefnet.co
        run: |
          nuget push xkpasswd.cli.${{ steps.gitversion.outputs.nuGetVersion }}.nupkg ${{ secrets.NUGET_KEY }} -Source ${{ secrets.NUGET_DESTINATION }} -NonInteractive
